### ISSUE TITLE
Error calculating CVSS3 when Integrity Requirement is set to High

### ISSUE THREAD

**Issue by 0secure** [ctxis/cvsslib#4]
When IR:H is included in the CVSS3 vector, an exception is thrown.  This does not occur for IR:L, IR:M, or IR:X

>>> from cvsslib import cvss2, cvss3, calculate_vector
>>> v = 'CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H/IR:L'
>>> calculate_vector(v,cvss3)
(7.5, 7.5, 7.2)
>>> v = 'CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H/IR:M'
>>> calculate_vector(v,cvss3)
(7.5, 7.5, 7.5)
>>> v = 'CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H/IR:H'
>>> calculate_vector(v,cvss3)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/st07572/dev/vmenv/lib/python3.6/site-packages/cvsslib/vector.py", line 62, in calculate_vector
    return run_calc(module.calculate, getter=_getter)
  File "/home/st07572/dev/vmenv/lib/python3.6/site-packages/cvsslib/utils.py", line 91, in run_calc
    result = function(*call_args, **kwargs)
  File "/home/st07572/dev/vmenv/lib/python3.6/site-packages/cvsslib/cvss3/calculations.py", line 145, in calculate
    environment_score = run_calculation(calculate_environmental_score, override=override)
  File "/home/st07572/dev/vmenv/lib/python3.6/site-packages/cvsslib/utils.py", line 91, in run_calc
    result = function(*call_args, **kwargs)
  File "/home/st07572/dev/vmenv/lib/python3.6/site-packages/cvsslib/cvss3/calculations.py", line 105, in calculate_environmental_score
    modified_impact_sub_score = run_calculation(calculate_modified_impact_sub_score)
  File "/home/st07572/dev/vmenv/lib/python3.6/site-packages/cvsslib/utils.py", line 91, in run_calc
    result = function(*call_args, **kwargs)
  File "/home/st07572/dev/vmenv/lib/python3.6/site-packages/cvsslib/cvss3/calculations.py", line 62, in calculate_modified_impact_sub_score
    return IMPACT_UNCHANGED_COEFFECIENT * modified
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'

**Comment by 0secure** [comment]
#5 created

**Comment by dgaus** [comment]
Thanks for the PR
